definitions:
    scripts:
        - &deploy_to_production
          name: Deploy to production
          script: |
              aws s3 sync ./your-first-flutter-app-to-appstore s3://labs.codemagic.io --delete --cache-control max-age=31536000,public
              aws cloudfront create-invalidation --distribution-id EP0IDLIGXES7G --paths '/*'

workflows:
    production:
        name: Deploy to production
        environment:
            groups:
                - aws-production
        scripts:
            - *deploy_to_production

