workflows:
  production:
    name: Deploy to production
    environment:
      groups:
        - aws-production
        - production
    instance_type: linux
    scripts:
      - name: Fetch Google Codelab tool
        script: |
          set -e
          # for now just hardcode for Linux on x86_64 for now
          curl https://github.com/googlecodelabs/tools/releases/download/v2.2.6/claat-linux-amd64 -o claat
          chmod +x claat

      - name: Build HTML static site
        script: |
          set -e
          ./claat export src/your-first-flutter-app-to-appstore/index.md

      - name: Deploy to production
        script: |
          set -e
          aws s3 sync ./your-first-flutter-app-to-appstore s3://labs.codemagic.io --delete --cache-control max-age=31536000,public
          aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths '/*'
